### ISSUE TITLE
Code highlight broken since sublime text 3 Build 3112 update

### ISSUE THREAD

**Issue by vqoph** [Medalink/laravel-blade#104]
Do i am the only one ?

<img width="616" alt="capture d ecran 2016-05-07 a 16 41 34" src="https://cloud.githubusercontent.com/assets/5341141/15117630/bb557e88-1608-11e6-9fc4-a1789a48db0f.png">

**Comment by ivandoric** [comment]
Same thing here.

**Comment by Bounoable** [comment]
Same here.

**Comment by Jaspur** [comment]
Oh, yea, it's not only me.

**Comment by ivandoric** [comment]
I reverted to 3111 until this issue is fixed.

**Comment by Jaspur** [comment]
@ivandoric link? i couldn't fit it on their site

**Comment by ivandoric** [comment]
https://download.sublimetext.com/Sublime%20Text%20Build%203111.dmg  -- But as I saw just now 3113 is out maybe that would fix things.

**Comment by Jaspur** [comment]
Thanks. No it's not fixing things the newest one.

**Comment by ivandoric** [comment]
@Jaspur Thanks. Good to know.

**Comment by jenky** [comment]
I'm using 3113 and it looks even worst, emmet is also broken on blade.

**Comment by Sotiris-k** [comment]
I'm also using 3114 and it is indeed completely broken

**Comment by svenluijten** [comment]
Issue still exists in 3114, single quotes inside text (eg. between `<p></p>` tags) are also being parsed as PHP: 
![Screenshot](https://cloud.githubusercontent.com/assets/11269635/15241823/c140dd8c-18f2-11e6-9025-c830152bf3fa.png)

**Comment by allenfantasy** [comment]
+1. It seems the plugin would parse anything as PHP code until it meet some punctuation sign like `'` or `.`

**Comment by exhtml** [comment]
same here! :(

**Comment by biu0w0** [comment]
the same 😞

**Comment by haxzorer** [comment]
Yup, same thing here for me (Sublime Text 3, Build 3114) on Mac OS X 10.10.5 (if it matters). Rolled back to build 3103 to make it work again.

**Comment by Jaspur** [comment]
@medalink, its still broken here...

**Comment by vqoph** [comment]
rolling back doesn't seems to be a right way to fix this, did you tried to understand from where the issue came from ?

**Comment by vqoph** [comment]
@medalink, seems to be fixed thx a lot !

**Comment by exhtml** [comment]
fixed! thank you very much!

**Comment by Skintillion** [comment]
I'm still having a problem with this even after updating Line 43 in the blade.sublime-syntax
