### ISSUE TITLE
comment with blade sintax in php regular files

### ISSUE THREAD

**Issue by elnato** [Medalink/laravel-blade#123]
it overrides my shortcut to comment
```
Route::get('/', function () {
    
    {{-- // return view('welcome'); --}}
    
});

```

**Comment by ethanbeyer** [comment]
I think my issue is the same in that ALL my PHP files use `{{--` and `--}}` for comments since upgrading to ST3 instead of the default `//` comments.

Is it possible that https://github.com/Medalink/laravel-blade/blob/master/blade.sublime-syntax#L4 needs to read:
```yaml
file_extensions: [blade, .blade.php]
```

...instead of:
```yaml
file_extensions: [blade, blade.php]
```

**Comment by zaynali53** [comment]
This has been resolved. 5a40a48

**Comment by ethanbeyer** [comment]
Probably a stupid question, but if I remove the Package and then reinstall the package, the reported erroneous behavior still occurs. Is this something I need to manually install in order to fix?

**Comment by zaynali53** [comment]
@ethanbeyer Oh. I just released a new version so right now package control didn't pick it up. Please wait or manually clone the repo to your sublime packages folder
